{
 "title": "Patroni info",
 "time": { "from": "2026-06-11T18:21:50.842Z", "to": "2026-06-11T18:45:56.277Z" },
 "panels": [
  {
   "title": "БД доступна",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "pg_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "primary status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "patroni_primary", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Связь с etcd",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "time() - patroni_dcs_last_seen", "legendFormat": "__auto" }
   ]
  }
 ]
}